createCardList
Leukipos/Capstone_Project pull request #8
Opened 2023-04-27 11:07 UTC by Leukipos

also..
- adjust Style
- link the Button on landing Page

2023-04-27 12:40 UTC, NikRoe requested changes
Hi Alex,

this is a very promising start! 

I left only a few notes. Please take a look at those and implement them :)

2023-04-27 12:40 UTC, NikRoe commented on components/StyledButton.js
>    border: 0px;
no need for a unit here :) 

```suggestion
  border: 0;
```

2023-04-27 12:40 UTC, NikRoe commented on components/StyledButton.js
>    box-shadow: 0 0px 25px 2px #EBE1CA, 0 0px 5px 0px #ffffff, inset 0 0px 25px 2px #EBE1CA;
you can remove those units

```suggestion
  box-shadow: 0 0 25px 2px #EBE1CA, 0 0 5px 0 #ffffff, inset 0 0 25px 2px #EBE1CA;
```

2023-04-27 12:40 UTC, NikRoe commented on pages/main.js
> +            <StyledCard>Modul Sechs</StyledCard>
you should consider making this part of the app dynamic at a later point and work with `.map()`

2023-04-27 20:23 UTC, Leukipos commented
Thank you for the help I solved the issues and i hope its fine now

2023-04-28 06:15 UTC, NikRoe approved these changes
LGTM 👍

2023-05-02 07:31 UTC, merged